


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json



### Identity Requests



###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/identities/by-id?identityId=ba13e4ae-31ed-4310-81c7-f8357508bb1c
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: yHjwBQejVSAFCSx10iq3DDRMZIiQ-5F_H4UpgT3cdQ58pogSrBzDZjeVbUUoPR4T5AeDPQ0qSbCgnqJSe7QQsQ_vTW9Olrx2

{
    "authority": "ADMIN",
    "email": "burgasvv@gmail.com",
    "password": "burgasvv",
    "enabled": true,
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич"
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: yHjwBQejVSAFCSx10iq3DDRMZIiQ-5F_H4UpgT3cdQ58pogSrBzDZjeVbUUoPR4T5AeDPQ0qSbCgnqJSe7QQsQ_vTW9Olrx2

{
    "authority": "USER",
    "email": "zagor@gmail.com",
    "password": "zagor",
    "enabled": true,
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Сергеевич"
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgvv@gmail.com burgasvv
X-Csrf-Token: DX2RLgks___pIf0vtRqZ-Em19u61wcMyMfFECuyLBc3dP9nFOBmpTzBNnMrEQ5lKhDetnHmC29fU8vUfBJB8OYq8M6--XO7w

{
    "id": "37ccc10c-3c58-4a52-a986-be4a8a5f7e7d",
    "email": "burgasvv@gmail.com"
}

###
DELETE /api/v1/identities/delete?identityId=9823930a-6979-4868-a02f-dcb7aa4a39b5
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/change-password?identityId=37ccc10c-3c58-4a52-a986-be4a8a5f7e7d&newPassword=burgasvv
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv111
X-Csrf-Token: xG-qfN_paVzJAw9AT2EPyHNiInXpzHHHalz3-T6REOgNAWPxp1eYTeePXWrkO2p3Lkw7qkUED0zcrRfqXjnHzFqldtk9MgGQ

###
DELETE /api/v1/identities/remove-images?identityId=37ccc10c-3c58-4a52-a986-be4a8a5f7e7d
    &mediaId=6332345d-3848-4dc5-889b-d79022ababf0&mediaId=348d5f40-9159-487d-81b5-21573b369557
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: zBhIyOaSUZyf7E-hgodlveFTP3WZg6SdBJWwIBDsL4C8hi-L_nopqoWjZqiyiHyVtqpR29hiEk39scWwPffWFSCPSeGK4xe6

###
PUT /api/v1/identities/enable-disable?identityId=e70b7812-36cd-4e3b-a18f-7142f09052bf&flag=true
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: Xeo8sGa-Ng2V4nY2afE9_GcE1rdjPGKvWH4RZ4vjDvyeDudXPNle0l-PVGi40hdUX9wJxAFg-48FDFuCbx9zBr6COM6tOtNn



### Brand Requests



###
GET /api/v1/brands
Host: localhost:9000
Accept: application/json

###
GET /api/v1/brands/by-id?brandId=4e1f070f-1bbd-40b7-9b5b-796a1a64a32e
Host: localhost:9000
Accept: application/json

###
POST /api/v1/brands/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: afDfuzz3k6novMcv-3tPEepZg9SxzYVSvxp9JL9NccNe6cN2DMK73gnBo5vF2qJNnlZ7I9w7ruyB-rV_3ikeQY8rRvFr2qcT

{
    "name": "Pagani",
    "description": "Описание и год создания бренда Pagani"
}

###
PUT /api/v1/brands/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: a-CJwDornzzrqWx5UZUbZhO2OJjRw4zFFzhFt0SIfGXYnZvPDtLtpQ8drw7GzwkbNLgvVCXUFaDh9Lzodgsm0nTuS1ftrv-q

{
    "id": "50b6537a-7ff7-44e0-9421-2f8751898d67",
    "description": "Описание и год создания бренда автомобилей Pagani"
}

###
DELETE /api/v1/brands/delete?brandId=50b6537a-7ff7-44e0-9421-2f8751898d67
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: e3xfxT6TgUJQZKVctNNjfIsJc7fIRv185blOx0wCvzHAy5vQHk47oAulsXB9AsA-0f5XTr1rXo_4cc1RhIotonxkiAP1-P-1



### Car Requests



###
GET /api/v1/cars
Host: localhost:9000
Accept: application/json

###
GET /api/v1/cars/by-id?carId=a37e5815-5535-4027-a9d4-cc86fc1d0686
Host: localhost:9000
Accept: application/json

###
POST /api/v1/cars/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: SYnJgVS1Az9FpMsBNv2XCeajXcOz5pen8scfVRzbib2UJPCsebD8uGWNNg1okvJgAdCjaNabcKLW0fSKx_8mZC3vvN7yHcCY

{
    "brandId": "32b0f48f-9e61-4c48-944d-d42d82ea9fb3",
    "model": "911",
    "characteristics": "Характеристики автомобиля модели 911 2015 года",
    "rentPrice": 1800.0,
    "free": true
}

###
PUT /api/v1/cars/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: UDGcqXXBzv5A1cPfAuzKVaYIYqYju60tV9rUTb5TVPv5f_TwNgf4kEHxrcpt7PHvYMH-MMdpT58Q2p0AYr_ie4ZmY52YScLJ

{
    "id": "d39a3a22-ddae-4fc1-b432-5c19fbb8453c",
    "model": "DB9-Coupe"
}

###
DELETE /api/v1/cars/delete?carId=d39a3a22-ddae-4fc1-b432-5c19fbb8453c
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: UDGcqXXBzv5A1cPfAuzKVaYIYqYju60tV9rUTb5TVPv5f_TwNgf4kEHxrcpt7PHvYMH-MMdpT58Q2p0AYr_ie4ZmY52YScLJ



### Rent Requests



###
GET /api/v1/rents/by-car?carId=a37e5815-5535-4027-a9d4-cc86fc1d0686
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/rents/by-identity?identityId=ba13e4ae-31ed-4310-81c7-f8357508bb1c
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/rents/by-id?rentId=b9de61f0-3316-4367-93cb-8732e4bc0be3
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/rents/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: GN5aDpBtbWQEsdBIMfkzNEpPd56uQ40JKt1feyeD4PI8BjUoe-Y7P6heVFcphrF8AtQHDXwqWqfMILwkSeVvQkWx0pZdNAIR

{
    "identityId": "ba13e4ae-31ed-4310-81c7-f8357508bb1c",
    "carId": "a37e5815-5535-4027-a9d4-cc86fc1d0686",
    "startTime": "2025-11-06T13:40",
    "endTime": "2025-11-07T14:00",
    "closed": false
}

###
POST /api/v1/rents/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic zagor@gmail.com zagor
X-Csrf-Token: bup8QjdMRuEowVkFrxZb1Q1qMrWJq-_Fp3MrmK2Z6K9aHNREXtNJewZ0c9MF92BkmDtvtD1SH9TsnIzokksSqZyt3cw8JeRw

{
    "identityId": "876885f6-034e-4478-8fde-addb05b11d80",
    "carId": "a136e4c4-0f0a-436f-b31b-66bc0300d392",
    "startTime": "2025-12-06T15:00",
    "endTime": "2025-12-07T17:00",
    "closed": false
}