


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json



### Identity Requests



###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json

###
GET /api/v1/identities/by-id?identityId=37ccc10c-3c58-4a52-a986-be4a8a5f7e7d
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: vMvakEtpTQuYWDoNIGeDOuBmB17KQMx4UWxgGOYS7Pwh3FSmhPO88npYL2q1YFluQUq3CtRUKmbycftVMA5TKNV3iMkY5GOQ

{
    "authority": "ADMIN",
    "email": "burgvv@gmail.com",
    "pass": "burgasvv",
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич"
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 289Jz76smCmW6OgcDWeFLxf-LaQgOE7468Jfutmxt7TVQPOG7qtxrofN-xy7iox5PEqxSyfJAJ1BC3jV3qNnib-Ggda2I8Sz

{
    "authority": "USER",
    "email": "zagor@gmail.com",
    "pass": "zagor",
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Сергеевич"
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgvv@gmail.com burgasvv
X-Csrf-Token: DX2RLgks___pIf0vtRqZ-Em19u61wcMyMfFECuyLBc3dP9nFOBmpTzBNnMrEQ5lKhDetnHmC29fU8vUfBJB8OYq8M6--XO7w

{
    "id": "37ccc10c-3c58-4a52-a986-be4a8a5f7e7d",
    "email": "burgasvv@gmail.com"
}

###
DELETE /api/v1/identities/delete?identityId=9823930a-6979-4868-a02f-dcb7aa4a39b5
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/change-password?identityId=37ccc10c-3c58-4a52-a986-be4a8a5f7e7d&newPassword=burgasvv
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv111
X-Csrf-Token: xG-qfN_paVzJAw9AT2EPyHNiInXpzHHHalz3-T6REOgNAWPxp1eYTeePXWrkO2p3Lkw7qkUED0zcrRfqXjnHzFqldtk9MgGQ

###
DELETE /api/v1/identities/remove-images?identityId=37ccc10c-3c58-4a52-a986-be4a8a5f7e7d
    &mediaId=6332345d-3848-4dc5-889b-d79022ababf0&mediaId=348d5f40-9159-487d-81b5-21573b369557
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
X-Csrf-Token: zBhIyOaSUZyf7E-hgodlveFTP3WZg6SdBJWwIBDsL4C8hi-L_nopqoWjZqiyiHyVtqpR29hiEk39scWwPffWFSCPSeGK4xe6